/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SolarTelemetry } from "./SolarTelemetry";
export * as factories from "./factories";
export { SolarTelemetry__factory } from "./factories/SolarTelemetry__factory";
