/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SolarTelemetryInterface extends Interface {
  getFunction(nameOrSignature: "publish"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Telemetry"): EventFragment;

  encodeFunctionData(
    functionFragment: "publish",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "publish", data: BytesLike): Result;
}

export namespace TelemetryEvent {
  export type InputTuple = [
    siteId: BigNumberish,
    timestamp: BigNumberish,
    wattHours: BigNumberish,
    batterySocBps: BigNumberish
  ];
  export type OutputTuple = [
    siteId: bigint,
    timestamp: bigint,
    wattHours: bigint,
    batterySocBps: bigint
  ];
  export interface OutputObject {
    siteId: bigint;
    timestamp: bigint;
    wattHours: bigint;
    batterySocBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SolarTelemetry extends BaseContract {
  connect(runner?: ContractRunner | null): SolarTelemetry;
  waitForDeployment(): Promise<this>;

  interface: SolarTelemetryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  publish: TypedContractMethod<
    [
      siteId: BigNumberish,
      timestamp: BigNumberish,
      wattHours: BigNumberish,
      batterySocBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "publish"
  ): TypedContractMethod<
    [
      siteId: BigNumberish,
      timestamp: BigNumberish,
      wattHours: BigNumberish,
      batterySocBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Telemetry"
  ): TypedContractEvent<
    TelemetryEvent.InputTuple,
    TelemetryEvent.OutputTuple,
    TelemetryEvent.OutputObject
  >;

  filters: {
    "Telemetry(uint256,uint256,uint256,uint256)": TypedContractEvent<
      TelemetryEvent.InputTuple,
      TelemetryEvent.OutputTuple,
      TelemetryEvent.OutputObject
    >;
    Telemetry: TypedContractEvent<
      TelemetryEvent.InputTuple,
      TelemetryEvent.OutputTuple,
      TelemetryEvent.OutputObject
    >;
  };
}
