/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  SolarTelemetry,
  SolarTelemetryInterface,
} from "../SolarTelemetry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "siteId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wattHours",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "batterySocBps",
        type: "uint256",
      },
    ],
    name: "Telemetry",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "siteId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "wattHours",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "batterySocBps",
        type: "uint256",
      },
    ],
    name: "publish",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101ac806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80631aa1589214610030575b600080fd5b61004a600480360381019061004591906100c9565b61004c565b005b837f7f7a33c98d52efc9f5e01b37c3fbfae891de4859a99acdca6566926e1c566fcc8484846040516100809392919061013f565b60405180910390a250505050565b600080fd5b6000819050919050565b6100a681610093565b81146100b157600080fd5b50565b6000813590506100c38161009d565b92915050565b600080600080608085870312156100e3576100e261008e565b5b60006100f1878288016100b4565b9450506020610102878288016100b4565b9350506040610113878288016100b4565b9250506060610124878288016100b4565b91505092959194509250565b61013981610093565b82525050565b60006060820190506101546000830186610130565b6101616020830185610130565b61016e6040830184610130565b94935050505056fea26469706673582212206c5d18393782182d642417365ba97bc986a8a42701c1ed65948e6a0eb0e57d8564736f6c63430008130033";

type SolarTelemetryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SolarTelemetryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SolarTelemetry__factory extends ContractFactory {
  constructor(...args: SolarTelemetryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SolarTelemetry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SolarTelemetry__factory {
    return super.connect(runner) as SolarTelemetry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SolarTelemetryInterface {
    return new Interface(_abi) as SolarTelemetryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SolarTelemetry {
    return new Contract(address, _abi, runner) as unknown as SolarTelemetry;
  }
}
